package com.buntupana.tmdb.feature.detail.domain.model

import com.panabuntu.tmdb.core.common.entity.MediaType
import java.time.LocalDate


sealed class MediaDetails(
    open val id: Long,
    open val title: String,
    open val posterUrl: String?,
    open val backdropUrl: String?,
    open val trailerUrl: String,
    open val overview: String,
    open val tagLine: String,
    open val releaseDate: LocalDate?,
    open val voteAverage: Int?,
    open val voteCount: Int?,
    open val runTime: Long,
    open val genreList: List<String>,
    open val ageCertification: String,
    open val creatorList: List<Person.Crew>,
    open val castList: List<Person.Cast>,
    open val crewList: List<Person.Crew>,
    open val recommendationList: List<com.panabuntu.tmdb.core.common.model.MediaItem>,
    open val isFavorite: Boolean,
    open val isWatchlisted: Boolean,
    open val userRating: Int?,
    open val mediaType: MediaType,
    open val isRateable: Boolean,
) {

    data class Movie(
        override val id: Long,
        override val title: String,
        override val posterUrl: String?,
        override val backdropUrl: String?,
        override val trailerUrl: String,
        override val overview: String,
        override val tagLine: String,
        override val releaseDate: LocalDate?,
        val localReleaseDate: String?,
        override val voteAverage: Int?,
        override val voteCount: Int?,
        override val runTime: Long,
        override val genreList: List<String>,
        override val ageCertification: String,
        override val creatorList: List<Person.Crew.Movie>,
        override val castList: List<Person.Cast.Movie>,
        override val crewList: List<Person.Crew.Movie>,
        override val recommendationList: List<com.panabuntu.tmdb.core.common.model.MediaItem>,
        val localCountryCodeRelease: String,
        override val isFavorite: Boolean,
        override val isWatchlisted: Boolean,
        override val userRating: Int?,
        override val isRateable: Boolean
    ) : MediaDetails(
        id = id,
        title = title,
        posterUrl = posterUrl,
        backdropUrl = backdropUrl,
        trailerUrl = trailerUrl,
        overview = overview,
        tagLine = tagLine,
        releaseDate = releaseDate,
        voteAverage = voteAverage,
        voteCount = voteCount,
        runTime = runTime,
        genreList = genreList,
        ageCertification = ageCertification,
        creatorList = creatorList,
        castList = castList,
        crewList = crewList,
        recommendationList = recommendationList,
        mediaType = MediaType.MOVIE,
        userRating = userRating,
        isFavorite = isFavorite,
        isWatchlisted = isWatchlisted,
        isRateable = isRateable
    )

    data class TvShow(
        override val id: Long,
        override val title: String,
        override val posterUrl: String?,
        override val backdropUrl: String?,
        override val trailerUrl: String,
        override val overview: String,
        override val tagLine: String,
        override val releaseDate: LocalDate?,
        override val voteAverage: Int?,
        override val voteCount: Int?,
        override val runTime: Long,
        override val genreList: List<String>,
        override val ageCertification: String,
        override val creatorList: List<Person.Crew.TvShow>,
        override val castList: List<Person.Cast.TvShow>,
        override val crewList: List<Person.Crew.TvShow>,
        override val recommendationList: List<com.panabuntu.tmdb.core.common.model.MediaItem>,
        val seasonList: List<Season>,
        val lastEpisode: Episode?,
        val nextEpisode: Episode?,
        val isInAir: Boolean,
        override val isFavorite: Boolean,
        override val isWatchlisted: Boolean,
        override val userRating: Int?,
        override val isRateable: Boolean
    ) : MediaDetails(
        id = id,
        title = title,
        posterUrl = posterUrl,
        backdropUrl = backdropUrl,
        trailerUrl = trailerUrl,
        overview = overview,
        tagLine = tagLine,
        releaseDate = releaseDate,
        voteAverage = voteAverage,
        voteCount = voteCount,
        runTime = runTime,
        genreList = genreList,
        ageCertification = ageCertification,
        creatorList = creatorList,
        castList = castList,
        crewList = crewList,
        recommendationList = recommendationList,
        mediaType = MediaType.TV_SHOW,
        userRating = userRating,
        isFavorite = isFavorite,
        isWatchlisted = isWatchlisted,
        isRateable = isRateable
    )
}
